# Generated by Django 5.0.2 on 2024-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/main_image/'),
        ),
    ]
