# Generated by Django 5.0.2 on 2024-03-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rate',
        ),
    ]
